### ISSUE TITLE
Hey @rpj09 I tried running the project locally, but couldn't install it. I installed all the dependencies and after running FRIDAY.py the output is none. What to do?

### ISSUE THREAD

**Issue by rpj09** [rpj09/FRIDAY-virtual-assistant#4]
Hey @rpj09 I tried running the project locally, but couldn't install it. I installed all the dependencies and after running FRIDAY.py the output is none. What to do?

_Originally posted by @anuragh2002 in https://github.com/rpj09/FRIDAY-virtual-assistant/issues/2#issuecomment-1272370023_

**Comment by manasvipriya** [comment]
Please assign me the issue @rpj09
